@baseUrl = http://localhost:3000
@userId = 

### Create Customer
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Prudence lynne",
  "email": "prud@gmail.com",
  "password": "lynn50"
}

### Create Admin
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@gmail.com",
  "password": "admin04",
  "role": "ADMIN"
}

### Get All Users
GET {{baseUrl}}/users

### Get User by ID
GET {{baseUrl}}/users/f1f8526e-b93f-4a39-a69d-94cb45351709

### Get Users by Role
GET {{baseUrl}}/users/role/CUSTOMER

### Get User by Email
GET {{baseUrl}}/users/email/cele@gmail.com

### Update User Info
PUT {{baseUrl}}/users/f1f8526e-b93f-4a39-a69d-94cb45351709
Content-Type: application/json

{
  "name": "Patience Lynne",
  "email": "pat@gmail.com"
}

### Change Password
POST {{baseUrl}}/users/change-password
Content-Type: application/json

{
  "userId": "0560c671-2a2d-439e-9ec7-c41ec7e7d6a3",
  "newPassword": "new23"
}

### Delete User by Email
DELETE {{baseUrl}}/users/3bc70544-b8b2-4e07-ae12-52946c25a935
